apiVersion: v1
kind: Namespace
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: openshift-hive
---
apiVersion: v1
kind: Service
metadata:
  name: hive-controller-manager-service
  namespace: openshift-hive
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: hive-controller-manager
  namespace: openshift-hive
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  replicas: 1
  revisionHistoryLimit: 4
  strategy:
    type: Rolling
  triggers:
  - type: "ConfigChange"
      #- type: "ImageChange"
      #imageChangeParams:
      #automatic: true
      #containerNames:
      #- "manager"
      #from:
      #kind: "ImageStreamTag"
    #name: "cluster-operator:latest"
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      # By default we are assuming a development setup with the image pushed to
      # the local registry. Pull policy should be Never in this case, it will be
      # modified in overrides for actual environments.
      - image: hive-controller:latest
        imagePullPolicy: Never
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        command:
        - /opt/services/manager
        - --log-level
        - debug
      terminationGracePeriodSeconds: 10